/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormCodeTermNumberTitleMeetsRouteImport } from './routes/form.$code.$term.$number.$title.$meets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormCodeTermNumberTitleMeetsRoute =
  FormCodeTermNumberTitleMeetsRouteImport.update({
    id: '/form/$code/$term/$number/$title/$meets',
    path: '/form/$code/$term/$number/$title/$meets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form/$code/$term/$number/$title/$meets': typeof FormCodeTermNumberTitleMeetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/$code/$term/$number/$title/$meets': typeof FormCodeTermNumberTitleMeetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form/$code/$term/$number/$title/$meets': typeof FormCodeTermNumberTitleMeetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form/$code/$term/$number/$title/$meets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/$code/$term/$number/$title/$meets'
  id: '__root__' | '/' | '/form/$code/$term/$number/$title/$meets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormCodeTermNumberTitleMeetsRoute: typeof FormCodeTermNumberTitleMeetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$code/$term/$number/$title/$meets': {
      id: '/form/$code/$term/$number/$title/$meets'
      path: '/form/$code/$term/$number/$title/$meets'
      fullPath: '/form/$code/$term/$number/$title/$meets'
      preLoaderRoute: typeof FormCodeTermNumberTitleMeetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormCodeTermNumberTitleMeetsRoute: FormCodeTermNumberTitleMeetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
